# Generated by Django 2.2.16 on 2023-02-19 15:46

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='Оценка от 1 до 10', validators=[django.core.validators.MinValueValidator(1, message='Рейтинг ниже допустимого'), django.core.validators.MaxValueValidator(10, message='Рейтинг выше допустимого')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validators.year_validator], verbose_name='Год создания произведения'),
        ),
    ]
